"""Initial migration

Revision ID: deca2ebbf069
Revises: 
Create Date: 2026-02-02 12:26:43.023496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'deca2ebbf069'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provision_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('config_type', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_root', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=15), nullable=True),
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['provision_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_mac_address'), 'devices', ['mac_address'], unique=True)
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('ticket_type', postgresql.ENUM('FORGOT_PASSWORD', 'PRIVILEGE_UPGRADE', 'ACCOUNT_UNLOCK', name='tickettype'), nullable=False),
    sa.Column('status', postgresql.ENUM('IN_PROGRESS', 'RESOLVED', 'REJECTED', name='ticketstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=50), nullable=True),
    sa.Column('secret', sa.String(length=50), nullable=True),
    sa.Column('secret_hint', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_index(op.f('ix_devices_mac_address'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('provision_configs')

    tickettype_enum = sa.Enum(name='tickettype')
    tickettype_enum.drop(op.get_bind(), checkfirst=True)
    
    ticketstatus_enum = sa.Enum(name='ticketstatus')
    ticketstatus_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
